# Generated by Django 4.1.2 on 2022-10-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_image_alter_media_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['timestamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog Profiles'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['timestamp'], 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['name'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Profiles'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials'),
        ),
    ]
